[kernel]
totalSpaceElements = 500
totalSpaceNodes = 501
totalTimeElements = 500
totalTimeNodes = 501
filename = "result"
result_dir = "./space02time01"
spaceDomain = [0.0, 50.0]
timeDomain = [0.0, 0.05]
spaceElemLength = 0.1
timeElemLength = 1.0e-4
elasticModulus = 1.0e+10
density = 2500.0
quadTypeForSpace = "GaussLegendreLobatto"
quadTypeForTime = "GaussLegendreLobatto"
baseInterpolationForSpace = "Lagrange"
spaceOrder = 2
baseInterpolationForTime = "Lagrange"
timeOrder = 1
verbosity = 0

[kernel.velocityLeft]
name = "velocityLeft"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "velocityLeft"

[kernel.tractionRight]
name = "tractionRight"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "tractionRight"

[kernel.initialVel]
name = "initialVel"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialVel"

[kernel.initialDisp]
name = "initialDisp"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialDisp"
