[linearElasticModel1]
name = "linearElasticModel"
# name of the model

elasticityType = "ISO"
# elasticity type, default is "ISO".

poissonRatio = 0.1
# Poisson's Ratio, it is necessary when elasticityType is ISO
youngsModulus = 1.0
# Young's Modulus, it is necessary when elasticityType is ISO

[linearElasticModel2]
name = "linearElasticModel"
# name of the model

isPlaneStress = true
# set it to true for plane-stress formulation
# the default is false

elasticityType = "ISO"
# elasticity type, default is "ISO".

poissonRatio = 0.1
# Poisson's Ratio, it is necessary when elasticityType is ISO
youngsModulus = 1.0
# Young's Modulus, it is necessary when elasticityType is ISO

[linearElasticModel3]
name = "linearElasticModel"
# name of the model

isPlaneStrain = true
# set it to true for plane-stress formulation
# the default is false

elasticityType = "ISO"
# elasticity type, default is "ISO".

poissonRatio = 0.1
# Poisson's Ratio, it is necessary when elasticityType is ISO
youngsModulus = 1.0
# Young's Modulus, it is necessary when elasticityType is ISO

[linearElasticModel4]
name = "linearElasticModel"
# name of the model

elasticityType = "ANISO"
# elasticity type, default is "ISO".

c = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, it can be 3 by 3

invC = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# inverse of C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, it can be 3 by 3

[linearElasticModel5]
name = "linearElasticModel"
# name of the model

elasticityType = "ANISO"
# elasticity type, default is "ISO".

isPlaneStress = true
# Plane stress

c = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

invC = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# inverse of C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

[linearElasticModel6]
name = "linearElasticModel"
# name of the model

elasticityType = "ANISO"
# elasticity type, default is "ISO".

isPlaneStrain = true
# Plane strain

c = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

invC = [
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
]
# inverse of C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

[linearElasticModel7]
name = "linearElasticModel"
# name of the model

elasticityType = "ANISO"
# elasticity type, default is "ISO".

isPlaneStress = true
# Plane stress

c = [
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
]
# C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

invC = [
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
]
# inverse of C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

[linearElasticModel8]
name = "linearElasticModel"
# name of the model

elasticityType = "ANISO"
# elasticity type, default is "ISO".

isPlaneStrain = true
# Plane strain

c = [
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
]
# C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part

invC = [
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
  [1.0, 2.0, 3.0],
]
# inverse of C elasticity tensor
# It should be 6 by 6
# For plane-stress and plane-strain case, we use only 3 by 3 part
