[kernel]
totalSpaceElements = 20
totalSpaceNodes = 21
totalTimeElements = 20
totalTimeNodes = 21
filename = "test-1"
result_dir = "./results"
spaceDomain = [0.0, 1.0]
timeDomain = [0.0, 1.0]
spaceElemLength = 0.05
timeElemLength = 0.05
elasticModulus = 2.0
density = 1.0
quadTypeForSpace = "GaussLegendreLobatto"
quadTypeForTime = "GaussLegendreLobatto"
baseInterpolationForSpace = "Lagrange"
spaceOrder = 1
baseInterpolationForTime = "Hierarchical"
timeOrder = 1
verbosity = 0

[kernel.velocityLeft]
name = "velocityLeft"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "velocityLeft"

[kernel.velocityRight]
name = "velocityRight"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "velocityRight"

[kernel.initialVel]
name = "initialVel"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialVel"

[kernel.initialDisp]
name = "initialDisp"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialDisp"

[kernel.bodyForce]
name = "bodyForce"
returnType = "Scalar"
argType = "SpaceTime"
numArgs = 2
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "bodyForce"
