[kernel]
totalSpaceElements = 10
totalSpaceNodes = 11
totalTimeElements = 40
totalTimeNodes = 41
filename = "result"
result_dir = "./results"
spaceDomain = [0.0, 5.0]
timeDomain = [0.0, 2.0]
spaceElemLength = 0.5
timeElemLength = 0.05
elasticModulus = 2.0
density = 1.0
quadTypeForSpace = "GaussLegendreLobatto"
quadTypeForTime = "GaussLegendreLobatto"
baseInterpolationForSpace = "Hierarchical"
baseTypeForSpace = "Monomial"
ipTypeForSpace = "GaussLegendreLobatto"
spaceOrder = 9
baseInterpolationForTime = "Hierarchical"
baseTypeForTime = "Monomial"
ipTypeForTime = "GaussLegendreLobatto"
timeOrder = 3
verbosity = 0

[kernel.velocityLeft]
name = "velocityLeft"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "velocityLeft"

[kernel.velocityRight]
name = "velocityRight"
returnType = "Scalar"
argType = "Time"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "velocityRight"

[kernel.initialVel]
name = "initialVel"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialVel"

[kernel.initialDisp]
name = "initialDisp"
returnType = "Scalar"
argType = "Space"
numArgs = 1
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "initialDisp"

# [kernel.bodyForce]
# name = "bodyForce"
# returnType = "Scalar"
# argType = "SpaceTime"
# numArgs = 2
# numReturns = 1
# luaScript = "./functions.lua"
# luaFunctionName = "bodyForce"
