#
# When a new pull request is made to main or master branch,
# there's an action that ensures the site builds successfully,
# without actually deploying.
# This job will be called test-deploy.
#
#
# name: Test deployment
#
# on:
#   pull_request:
#     branches:
#       - master
#       - main
#     # Review gh actions docs if you want to further define triggers, paths, etc
#     # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
#
# jobs:
#   test-deploy:
#     name: Test deployment
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 21
#           cache: yarn
#
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile
#       - name: Test build website
#         run: NODE_OPTIONS=--max-old-space-size=4096 yarn build
